export const ACCESS_TOKEN_EXPIRATION_TIME = '5d';
export const CLIENT_ACCESS_TOKEN_EXPIRATION_TIME = '5d';
export const JWT_CLIENT_REFRESH_EXPIRATION_TIME = '6d';
export const JWT_REFRESH_EXPIRATION_TIME = '6d';
