export enum AuthActionTypes {
  // Auth actions
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  GET_TOKEN = 'GET_TOKEN',
  PARSE_TOKEN = 'PARSE_TOKEN',
  SET_TOKEN = 'SET_TOKEN',
  CHECK_TOKEN = 'CHECK_TOKEN',
  DELETE_TOKEN = 'DELETE_TOKEN',

  // Auth Getters
  IS_AUTHENTICATED = 'IS_AUTHENTICATED',
  AUTH_USER = 'AUTH_USER',
  AUTH_TOKEN = 'AUTH_TOKEN',
}

export enum ComplaintsActionTypes {
  CREATE_COMPLAINT = 'CREATE_COMPLAINT',
  GET_COMPLAINTS = 'GET_COMPLAINTS',
  GET_COMPLAINT = 'GET_COMPLAINT',
  GET_BULK_COMPLAINTS = 'GET_BULK_COMPLAINTS',
  UPDATE_COMPLAINT = 'UPDATE_COMPLAINT',
  DELETE_COMPLAINT = 'DELETE_COMPLAINT',
  SAVE_COMPLAINT = 'SAVE_COMPLAINT',
  GET_LOCAL_COMPLAINTS = 'GET_LOCAL_COMPLAINTS',

  // Complaints Getters
  COMPLAINTS_GETTER = 'COMPLAINTS_GETTER',
}

export enum AgenciesActionTypes {
  GET_AGENCIES = 'GET_AGENCIES',
  GET_AGENCY = 'GET_AGENCY',
  CREATE_AGENCY = 'CREATE_AGENCY',
  UPDATE_AGENCY = 'UPDATE_AGENCY',
  DELETE_AGENCY = 'DELETE_AGENCY',

  // Agencies Getters
  AGENCIES_GETTER = 'AGENCIES_GETTER',
}

export enum CategoriesActionTypes {
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_CATEGORIES_WITH_COMPLAIN_COUNT = 'GET_CATEGORIES_WITH_COMPLAIN_COUNT',
  GET_CATEGORY = 'GET_CATEGORY',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',

  // Categories Getters
  CATEGORIES_GETTER = 'CATEGORIES_GETTER',
}

export enum UsersActionTypes {
  GET_USERS = 'GET_USERS',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  GET_ANALYTICS = 'GET_ANALYTICS', // For Analytics

  // Users Getters
  USERS_GETTER = 'USERS_GETTER',
}
